name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, zip, phar
    
    - name: Install dependencies
      run: composer install --no-dev --optimize-autoloader
    
    - name: Build application
      run: |
        chmod +x build.sh
        ./build.sh
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: builds/zeri
        body: |
          ## Installation
          
          ### Install Script (Recommended)
          ```bash
          curl -fsSL https://raw.githubusercontent.com/hadefication/zeri/main/scripts/install.sh | bash
          ```
          
          ### Manual Installation
          ```bash
          curl -L https://github.com/hadefication/zeri/releases/download/${{ github.ref_name }}/zeri -o /usr/local/bin/zeri
          chmod +x /usr/local/bin/zeri
          ```
          
          ### Usage
          ```bash
          zeri init
          zeri generate claude
          zeri add-spec "feature-name"
          ```
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}